feat: add rounded corners
dvx/lofi pull request #307
Opened 2024-01-06 05:37 UTC by marriaga158

2024-01-09 02:16 UTC, stamoun commented
Thanks a lot for taking the time to do this!

I should be able to have a look at your PR this week.

2024-01-09 22:02 UTC, stamoun commented
I noticed another issue (other than the bars and menu buttons disappearing).
When I switched to one of my other monitors on my Mac, the transparent background was white as follows:

![image](https://github.com/dvx/lofi/assets/15142541/d289fdd6-2011-4eeb-8696-2b56ae04e893)

Not sure if it's a Mac only issue (haven't tested on windows).
I don't think it's a showstopper for this feature though. I'd create a new issue for that.

2024-01-09 22:03 UTC, stamoun requested changes

2024-01-09 22:03 UTC, stamoun commented on src/renderer/windows/settings/window-settings.tsx
> +import { MACOS_CORNER_RADIUS, MAX_BAR_THICKNESS, MAX_CORNER_RADIUS, WIN_11_CORNER_RADIUS } from '../../../constants';
```suggestion
import { MAX_BAR_THICKNESS, MAX_CORNER_RADIUS } from '../../../constants';
```

2024-01-09 22:03 UTC, stamoun commented on src/renderer/windows/settings/window-settings.tsx
> +
Delete

2024-01-09 22:03 UTC, stamoun commented on src/renderer/windows/settings/window-settings.tsx
> +              defaultValue={calcDefaultRadius()}
```suggestion
              defaultValue={DEFAULT_SETTINGS.cornerRadius}
```

2024-01-09 22:04 UTC, stamoun commented
Good stuff though, I like the rounded corners! 🤗

2024-01-11 14:39 UTC, stamoun commented on src/constants.ts
> +export const MAX_CORNER_RADIUS = 20;
Thinking back on this, a full round (circle) Lofi is probably not needed, limiting to whatever percentage is enough to access the menu buttons should be ok (25%?)

2024-01-13 21:30 UTC, marriaga158 commented
![image](https://github.com/dvx/lofi/assets/22554314/50238e29-2972-4055-a8cc-633c774bfb58)

Updated with the suggested changes, there's still a lingering issue where on larger sizes the corner radius can clip the menu buttons. Going to investigate if there's a way to automatically move them inwards as a solution

2024-01-15 18:26 UTC, stamoun approved these changes

2024-01-20 15:29 UTC, merged